name: Publish Docker image
on:
  push: { branches: ['master'] }

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']
        drupal: ['8', '9']
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./drupal-ci
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/drupal-ci:${{ matrix.drupal }}-php${{ matrix.php }}
        build-args: |
          PHP_VERSION=${{ matrix.php }}
          DRUPAL_IMAGE_TAG=${{ matrix.drupal }}
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
